build-job:
    stage: build
    tags:
        - docker
    script:
        - echo "Building the project... $GITLAB_USER_LOGIN!."

test-job1:
    stage: test
    tags:
        - docker
    script:
        - echo "Testing the project..."

test-job2:
    stage: test
    tags:
        - docker
    script:
        - echo "This job tests something, but takes more time than test-job1."
        - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
        - sleep 20

deploy-prod:
    stage: deploy
    tags:
        - docker
    script:
        - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    environment: production
